### ISSUE TITLE
NaN Value as Output 

### ISSUE THREAD

**Issue by yh08** [pln-fing-udelar/fast-krippendorff#9] opened 2020-04-01 19:05 UTC
as I understood, the k-alpha should be taking nan values as well and ignores it. However, I received NaN values as output, which actually can't be, right? 
The reliability data looks as follows: 
[[0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1] [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, 0, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]]

Also I receive an Error message: 
**RuntimeWarning**: invalid value encountered in double_scalars
  return 1 - np.sum(o * d) / np.sum(e * d)

Meanwhile the other scores look pretty reasonable to me, although some of them also have a lot of NaN values (see screenshot). 

Thanks in advance!

**Comment by bryant1410** [comment] 2020-04-02 02:34
Can you share exactly the code that you execute to reproduce this issue?

**Comment by yh08** [comment] 2020-04-02 06:26
Thank for getting back so fast!
the dataframe I worked with consists of annotator label as columns & the known_labels as last column. Index is the ID. When calculating each worker-worker agreement, I also received lot of NaN values.
![ww-agreement](https://user-images.githubusercontent.com/49392305/78217087-93775880-74bb-11ea-84ad-a43cfed41d00.png)
 

````
# # Known Answers Agreement

# In[24]:


def file2df_known_ans(filename):
    '''reads a csv file and returns a df with worker answers as columns'''
    df = pd.read_csv(filename, sep = ',', encoding = 'utf-8')
    df_assorted = df[['HITId', 'WorkerId', 'Answer.semantic-similarity.label', 'Input.similarity_label']]
    df_worker_col = df_assorted.pivot(index = 'HITId', columns='WorkerId', values = 'Answer.semantic-similarity.label')
    df_w = df_worker_col.reset_index()
    df_knownans_col = df_assorted.drop_duplicates(subset=['HITId', 'Input.similarity_label'], keep='first')
    df_ans = df_knownans_col.drop(columns=['WorkerId', 'Answer.semantic-similarity.label'])
    df = pd.merge(df_w, df_ans, how='inner', on='HITId')
    df_nein = df.replace(to_replace ="nein", value =0)
    df_obj = df_nein.astype(object)
    df_ja = df_obj.replace(to_replace ="ja", value =1) 
    return df_ja.astype(object)

def IAA_known_score(workers_ans, known_answer):
    reliability_data = [workers_ans, known_answer]
    score = krippendorff.alpha(reliability_data=reliability_data, level_of_measurement='nominal')
    return score


# In[34]:


df_workers_known_ans = file2df_known_ans(filename).astype(object)


# In[26]:


known_ans = df_workers_known_ans['Input.similarity_label'].values.tolist()


# In[27]:


def compare_known_ans(all_workers, known_ans, df_workers_known_ans): 
    results = list()
    for worker in all_workers:
        list_w = df_workers_known_ans[worker].values.tolist()
        score = IAA_known_score(list_w, known_ans)
        results.append(score)
    return results


# In[35]:


score_known_ans = compare_known_ans(all_workers, known_ans, df_workers_known_ans)


# In[36]:


df_score_known_ans = pd.DataFrame(score_known_ans, index=all_workers)


# In[37]:


df_score_known_ans


# In[39]:


worker = df_workers_known_ans['A3AK3UL0UCNVKE'].values.tolist()


# In[40]:


print(known_ans, worker)
```
`

**Comment by bryant1410** [comment] 2020-04-03 14:29
I'm trying to run the following you sent but it doesn't work:

```python
def file2df_known_ans(filename):
    '''reads a csv file and returns a df with worker answers as columns'''
    df = pd.read_csv(filename, sep = ',', encoding = 'utf-8')
    df_assorted = df[['HITId', 'WorkerId', 'Answer.semantic-similarity.label', 'Input.similarity_label']]
    df_worker_col = df_assorted.pivot(index = 'HITId', columns='WorkerId', values = 'Answer.semantic-similarity.label')
    df_w = df_worker_col.reset_index()
    df_knownans_col = df_assorted.drop_duplicates(subset=['HITId', 'Input.similarity_label'], keep='first')
    df_ans = df_knownans_col.drop(columns=['WorkerId', 'Answer.semantic-similarity.label'])
    df = pd.merge(df_w, df_ans, how='inner', on='HITId')
    df_nein = df.replace(to_replace ="nein", value =0)
    df_obj = df_nein.astype(object)
    df_ja = df_obj.replace(to_replace ="ja", value =1) 
    return df_ja.astype(object)

def IAA_known_score(workers_ans, known_answer):
    reliability_data = [workers_ans, known_answer]
    score = krippendorff.alpha(reliability_data=reliability_data, level_of_measurement='nominal')
    return score

df_workers_known_ans = file2df_known_ans(filename).astype(object)
known_ans = df_workers_known_ans['Input.similarity_label'].values.tolist()


def compare_known_ans(all_workers, known_ans, df_workers_known_ans): 
    results = list()
    for worker in all_workers:
        list_w = df_workers_known_ans[worker].values.tolist()
        score = IAA_known_score(list_w, known_ans)
        results.append(score)
    return results

score_known_ans = compare_known_ans(all_workers, known_ans, df_workers_known_ans)
```

Could you send me code that I could run to reproduce the issue?

**Comment by bryant1410** [comment] 2020-04-19 22:26
I'm closing this as we talked via email and there was a problem with the input. Please, feel free to open an issue again if you have problems. Thanks for the feedback!

**Closed by bryant1410** 2020-04-19 22:26 UTC

**Comment by kovaacs** [comment] 2020-11-19 17:33
I'm experiencing the exact same issue. What was the problem with the input data?

**Comment by bryant1410** [comment] 2020-11-21 19:12
> I'm experiencing the exact same issue. What was the problem with the input data?

The problem was that the input `reliability_data` didn't have a `(M, N)` shape. The doc says:

```
    Parameters
    ----------
    reliability_data : array_like, with shape (M, N)
        Reliability data matrix which has the rate the i coder gave to the j unit, where M is the number of raters
        and N is the unit count.
        Missing rates are represented with `np.nan`.
        If it's provided then `value_counts` must not be provided.
    value_counts : ndarray, with shape (N, V)
        Number of coders that assigned a certain value to a determined unit, where N is the number of units
        and V is the value count.
        If it's provided then `reliability_data` must not be provided.
```
